### ISSUE TITLE
Video Quality 

### ISSUE THREAD

**Issue by mjain234** [Sovan22/Tokeii#1]
Hey, I just found this app through one of the telegram groups and have been enjoying it since then. It is very simple to use and the UI is minimalistic too. 

There are some flaws too like there are no settings for changing the video quality or download option. It will be great if there are such options in future builds too.

Also, ![here](https://github.com/Sovan22/Tokeii/assets/70900505/c3889b8d-2648-44f9-b5b2-93e0f45edbd9) you can see the video quality is of 960p, so is it by default 960p or we can change it too?

**Comment by Sovan22** [comment]
@mjain234 The video quality is changed automatically based on your network speed and bandwidth.
Also, I will add the video quality selector feature by today.

**Comment by Sovan22** [comment]
Updated the app with quality selection feature

**Comment by mjain234** [comment]
Sometimes, the "Quality" selection is not shown for every movie and it's by default set to 1080p. Is it a bug?

![Screenshot_20231128-125923.png](https://github.com/Sovan22/Tokeii/assets/70900505/a7efbcbf-b855-4d7f-ad84-f43e519ef639)

**Comment by Sovan22** [comment]
@mjain234 quality selector is not available for the superstream source yet, this must be playing from that source. I will add it in future releases

**Comment by mjain234** [comment]
Here again I faced some kind of issue with the video quality. While selecting for the video quality, I have already chosen 1080p, but on video player it is showing 802p. What does it indicate? https://github.com/Sovan22/Tokeii/assets/70900505/a745c5e6-ce6b-49a7-855d-30ffb440ed3a

**Comment by Sovan22** [comment]
@mjain234 The quality is changed but this indicates that the original dimensions sent with the 1080p label from the source are different from actual 1920*1080. In these type of sources the original dimensions are sometimes different and random like 1096 * 732, 1028 * 608. I will streamline these so that these random numbers are not shown and known qualities like 1080p, 720p are shown

**Comment by Sovan22** [comment]
Now quality selection is available for every source with proper quality tags
Fixed in update v1.0.8
