### ISSUE TITLE
Persian subtitle

### ISSUE THREAD

**Issue by Javadsh70** [Sovan22/Tokeii#10]
Hello dear developer(s)
Would you please add Persian subtitles to the movies and series , thank you

**Comment by Sovan22** [comment]
@Javadsh70 working on adding open subtitles to provide more subs

**Comment by Javadsh70** [comment]
> @Javadsh70 working on adding open subtitles to provide more subs

@Sovan22 
Thank you for your great job .
If it is possible add Subscene.com source.
It covers more and update subs.

**Comment by Sovan22** [comment]
Opensubtitles added for wide range of subtitles
