### ISSUE TITLE
Current library is limited to 20 items (movies / series) per row, please add more content per row or a drop down with (updated) content 

### ISSUE THREAD

**Issue by Ridwaan112** [Sovan22/Tokeii#11]

**Comment by Uvdon** [comment]
Add genre browsing as well. Also if ur reading this, please be aware that there are a few minor bugs- next button doesn't work properly; no save option for  faster browsing (especially for shows); talking about tv shows, if for example I'm on 3rd season of a show, if I go back, it doesn't remember I was on 3rd season and I keep having to change season option. Lastly, the auto brightness sucks, I don't understand why it was invented in a video player, like it takes literally 1 sec to change brightness just by dragging down on android.

**Comment by Sovan22** [comment]
Will try to address all of these issues in the next update. You can change the brightness by swiping down on the left side while the video is playing.

**Comment by Uvdon** [comment]
Yeah, but if I change the brightness from my phone settings, it doesn't accept it. It only accepts video players brightness setting, which sucks honestly because I the brightness on the player is limited

**Comment by Sovan22** [comment]
Increased library content per row in update 1.1.1

**Comment by Ridwaan112** [comment]
> Increased library content per row in update 1.1.1

Great work 👏

Thank you
