### ISSUE TITLE
Source Request - Indian Content

### ISSUE THREAD

**Issue by stingyman12** [Sovan22/Tokeii#14]
Could you please consider adding the following websites to the list of providers for this app?

[iBomma](https://remo.ibomma.pw/telugu-movies/): This site offers content in the Telugu language from India.
[MovierulzHD](https://movierulzhd.host/): This website features content in all Indian languages.

Thank you for your consideration.

**Comment by Sovan22** [comment]
Closing the issue already have a movierulzHD source request opened #13 . I might not do the iBomma one but work in progress for movierulzHD
