### ISSUE TITLE
(bug) Large List Handling Crashes

### ISSUE THREAD

**Issue by OshekharO** [Sovan22/Tokeii#17]
When I opened the application and searched for 12Th Man (2022) and after opening it the player initialise then application crashes. Also when I search for other movie the player just keeps on loading even after waiting 5 minutes, same for firestick as well as on mobile. Also I think navigation bar should be on left side in Android tv instead of bottom ( just like cloudstream ) or jiocinema.

**Comment by Sovan22** [comment]
@OshekharO do you have any vpn on while using the app?

**Comment by OshekharO** [comment]
> @OshekharO do you have any vpn on while using the app?

No, nothing also the problem I am facing is with the player ( probably ). Or Hindi extension maybe it's blocking my ISP 🤔

**Comment by Sovan22** [comment]
Yes that might be it, I will try adding a proxy for that one and provide with an update soon. Could you also name some of the movies you tried which were loading for long time. I will check from my end, if there is any issue

**Comment by OshekharO** [comment]
> Yes that might be it, I will try adding a proxy for that one and provide with an update soon. Could you also name some of the movies you tried which were loading for long time. I will check from my end, if there is any issue

No issues I tried after clearing data it's working perfectly fine but Hindi movies are not working so most probably the issue is with extension

**Comment by OshekharO** [comment]
Also when I am searching shinchan in tv series and opening it, the application force close itself 😞 maybe not able to handle large episode list or something.
