### ISSUE TITLE
App not working 

### ISSUE THREAD

**Issue by Uvdon** [Sovan22/Tokeii#22]
App isn't working. Plz fix

**Comment by DarkCrypt** [comment]
Same. App continuously crashing on open.

**Comment by Sovan22** [comment]
Working on a fix, will try to update by this week.

**Comment by safdar9633** [comment]
Waiting for the fix <3

**Comment by Sovan22** [comment]
Fixed , update and check

**Comment by DarkCrypt** [comment]
App (v1.1.3) is working, thank you!
