### ISSUE TITLE
NO AVAILABLE LINKS ON MOST OF THE CONTENT 

### ISSUE THREAD

**Issue by Ridwaan112** [Sovan22/Tokeii#24]
Hi, please resolve no links, needs and update and links to better servers - SoraStream has some solid server links please incorporate 🙏

**Comment by Sovan22** [comment]
@Ridwaan112 Working on a fix, might release an update within the next week

**Comment by monjurulkarim** [comment]
@Sovan22 Any news on the update?

**Comment by Sovan22** [comment]
@monjurulkarim updated check in releases
