### ISSUE TITLE
Some movies not available

### ISSUE THREAD

**Issue by mjain234** [Sovan22/Tokeii#5]
As you can see [here](https://i.imgur.com/Xl8GFZR.mp4), whenever I click to watch any movie, it says "not available". So what does it actually mean?

**Comment by Sovan22** [comment]
@mjain234 When there is no available video link it shows not available, but these movies should be available, might be due to changes in the source I am using. Will check it out and update if necessary

**Comment by mjain234** [comment]
I was watching this movie named "Blue Beetle" and it was working perfectly until today showing "Not Available" as you can see [here](https://github.com/Sovan22/Tokeii/assets/70900505/20270301-6523-4bef-9ef4-270c6d13c95f). Why it is happening like this?

**Comment by Sovan22** [comment]
@mjain234 working on a fix, will soon provide an update

**Comment by Sovan22** [comment]
Fixed the sources causing the problem

**Comment by mjain234** [comment]
Why [these](https://github.com/Sovan22/Tokeii/assets/70900505/699c24e4-59e7-417b-a2b3-460f33028683) movies are not playable? Whenever clicking to watch, after certain point of time it backs out automatically.

**Comment by Sovan22** [comment]
@mjain234 can you tell me the version of the app you are using

**Comment by mjain234** [comment]
![Screenshot_20231201-133033.png](https://github.com/Sovan22/Tokeii/assets/70900505/2daece5e-ee33-4c23-a5b2-ad08b7107b25)

Latest one..

**Comment by Sovan22** [comment]
@mjain234 Can you try running any other Hindi movie and tell if it's working

**Comment by mjain234** [comment]
Some of them are working as you can see [here](https://github.com/Sovan22/Tokeii/assets/70900505/6e6c6530-0493-4765-8d36-4969638ee351) but what is the source of all these videos? Because as you can in the video, it is starting with an ad like Rajabet & Parimatch.

**Comment by Sovan22** [comment]
The source is dudefilms, it has some 1xbet ads in some movies, I will try to add auto skip for this specific source

**Comment by Sovan22** [comment]
@mjain234 if these are working the fukrey3 one should also be available. I checked it just now.

**Comment by mjain234** [comment]
https://drive.google.com/file/d/1d7iUMfW_21wPcl5Vw7jx3uiiFkfbwJwT/view 

Something is not right here, I think the source for Hindi movies is creating this issue

**Comment by Sovan22** [comment]
@mjain234 I am not able to access the drive file

**Comment by mjain234** [comment]
> @mjain234 I am not able to access the drive file 

https://drive.google.com/file/d/1d7iUMfW_21wPcl5Vw7jx3uiiFkfbwJwT/view

See if this is accessible?

**Comment by Sovan22** [comment]
@mjain234 I added a recent update try using that and turn off any vpn or DNS, if still the problem persists. I will look into the Hindi source or most probably change it.Also, thank you for testing the app such rigorously. You have helped me remove countless bugs.

**Comment by mjain234** [comment]
Still I guess there is a problem. After the update, I was able to watch Fukrey 3 until today, it now says "Not Available" and other Hindi movies still not able to run properly.

**Comment by Sovan22** [comment]
@mjain234 okay I will change the hindi source in the next update. But the video you shared is only showing your PC

**Comment by mjain234** [comment]
> @mjain234 okay I will change the hindi source in the next update. But the video you shared is only showing your PC

Sorry for the previous file, check this [out](https://drive.google.com/file/d/1d7iUMfW_21wPcl5Vw7jx3uiiFkfbwJwT/view)
