### ISSUE TITLE
🪄[FR]: Android TV Support

### ISSUE THREAD

**Issue by DarkCrypt** [Sovan22/Tokeii#7]
I installed the app on Android TV 10 and a lot of it works already. It's usable but needs improvement since it isn't intended for tv.

**Comment by Sovan22** [comment]
@DarkCrypt I will definitely try to optimize it for Android TV.

**Comment by DarkCrypt** [comment]
Ok, awesome! I'm not sure what's all necessary to make the app more compatible.

Presently, the app only has portrait mode which makes it harder to test. Can landscape be implemented? This would also be good for tablets.

**Comment by Sovan22** [comment]
Added landscape and tv support. 
Feel free to open an issue if you encounter any problem regarding this
