### ISSUE TITLE
Subtitles and gestures option 

### ISSUE THREAD

**Issue by Uvdon** [Sovan22/Tokeii#8]
Turning off subtitles option doesn't work, also I don't understand why it's turned on by default cuz many people like myself don't like that. Another thing I would appreciate is if we have options to turn off gestures (brightness, volume and double tap). 

Thank u

**Comment by Sovan22** [comment]
@Uvdon For disabling gestures you can use the lock mode provided. I will fix the sub problem and provide an update.

**Comment by Uvdon** [comment]
Thank you
