### ISSUE TITLE
Yomovies source request

### ISSUE THREAD

**Issue by Uvdon** [Sovan22/Tokeii#9]
Just like cloudstream, this app also my get into legal issues. A way to prevent this is by adding repositorys just like.cloudstream. Also, if possible would u please kindly add yomovies, cuz it has koffe with Karan and many Indians web series I like watching. Thank u

**Comment by Sovan22** [comment]
@Uvdon I will switch to extension based sources in future. Also could you tell me the specific site of yomovies you're talking about

**Comment by Uvdon** [comment]
It's just yomovies.com. Im not programmer and don't know nothing about no source code. But cloudstream has it and thought you would be able to  add that. 
Thank u

**Comment by IndusAryan** [comment]
eh, yomovies changes domain frequently , my extension is clone of yomovies but rebranded as pr movies , you can check extractor and scraper there

https://github.com/IndusAryan/Aryans-Repo

**Comment by Sovan22** [comment]
@IndusAryan thanks for the help. I will soon add this source

**Comment by Sovan22** [comment]
Added PRmovies in the latest update
